name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  build-plrl:
    name: Build polars-readlines
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-C target-cpu=x86-64-v3"
      - name: Install dependencies
        run: python -mpip install maturin[zig]
      - name: Build sdist
        run: maturin sdist --out dist
      - name: Build wheels
        run: maturin build --release --out dist --compatibility manylinux2014 --zig
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
